### ISSUE TITLE
Create an independent cubature account in GitHub (like we find for numpy, scipy etc)

### ISSUE THREAD

**Issue by saullocastro** [saullocastro/cubature#11]
@antonl  since this is getting bigger, I itend to move the repository to a new GitHub account called "cubature" and add we both as admin.

What do you think?

**Comment by saullocastro** [comment]
I've done this already for the repositories below:

https://github.com/desicos/desicos
https://github.com/compmech/compmech

**Comment by saullocastro** [comment]
If we decide to do this the change should be definitive after we communicate Prof. Steven G. Johnson to change [this wiki](http://ab-initio.mit.edu/wiki/index.php/Cubature).

**Comment by antonl** [comment]
Sure, that sounds fine. That would make a few things easier and also allow us to mirror the cubature code there (with permission of course).

**Comment by saullocastro** [comment]
There will be a problem, there is a user https://github.com/cubature already...

**Comment by saullocastro** [comment]
Anywaz @antonl  I added you as a collaborator so you won't need so submit a pull request to perform any changes. You can directly commit to the master repository instead.
