### ISSUE TITLE
Continuous integration tests

### ISSUE THREAD

**Issue by antonl** [saullocastro/cubature#13]
It would be nice to implement continuous integration tests to catch bugs like #12 early. Travis CI is free for open-source projects; we should consider adding the appropriate hooks to our commits.

**Comment by saullocastro** [comment]
I fully support your opinion. Let's start to work on this! I'll have a look
how does Travis CI works...

**Comment by antonl** [comment]
It seems pretty easy to setup, but I think you have to do it. I tried this morning, but it can only access my accounts. I can play with it in my fork for the time being though.

**Comment by saullocastro** [comment]
Now you can do it too, you are admin of this repository

2015-10-01 18:46 GMT-03:00 Anton Loukianov <notifications@github.com>:

**Comment by antonl** [comment]
Yes, but because you're the owner, this repo doesn't show up on Travis CI on my account.

**Comment by saullocastro** [comment]
Thanks for explaining... I am configuring it right now

**Comment by saullocastro** [comment]
Ok @antonl  it is already active, we just need to configure the .travis.yml file.

**Comment by antonl** [comment]
Looks like it is working now!

Travis:  [![Build Status](https://travis-ci.org/saullocastro/cubature.svg?branch=master)](https://travis-ci.org/saullocastro/cubature)

**Comment by saullocastro** [comment]
@antonl  great! :+1:

**Comment by saullocastro** [comment]
Perhaps we should release 0.13.1

**Comment by antonl** [comment]
I'd like to add the "slow" cubature_two unit test back in before we do that.

**Comment by saullocastro** [comment]
All right then

**Comment by antonl** [comment]
Created PR #14 to add cubature_two back in.
