### ISSUE TITLE
Citing cubature

### ISSUE THREAD

**Issue by AEljarrat** [saullocastro/cubature#22]
Dear @saullocastro 

How should we cite your work in an academic publication? I have failed to find instructions or a related paper in your documentation.

Best regards,
Alberto.

**Comment by saullocastro** [comment]
@AEljarrat Please, cite the publications that used the wrapper:

Used to integrate tangent stiffness matrices in computational solid mechanics
---
Castro, S.G.P. et al. "Evaluation of non-linear buckling loads of geometrically imperfect
composite cylinders and cones with the Ritz method". Composite Structures, Vol. 122, 284-299, 2015.

Castro, S.G.P. et al. "A semi-analytical approach for linear and non-linear analysis of unstiffened laminated composite cylinders and cones under axial, torsion and pressure loads". Thin-Walled Structures, Vol. 90, 61-73, 2015.

The Python wrapper should be cited as:
---
Castro, S.G.P.; Loukianov, A.; et al. "Python wrapper for Cubature: adaptive multidimensional integration". On-line: https://github.com/saullocastro/cubature/releases, Version 0.13.3, 2017.
(change the version and year if needed)

**Comment by saullocastro** [comment]
I will push a commit to close this one, changing the README.rst file

**Comment by saullocastro** [comment]
closed with commit #f0fcfd5
