### ISSUE TITLE
Installing from pypi fails 

### ISSUE THREAD

**Issue by jbvsmo** [saullocastro/cubature#28]
I'm running this

    python3 -m pip install cubature --upgrade

Result:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/s9/lz602rh965395lw50zg7nhzh0000gn/T/pip-install-8m8jt094/cubature/setup.py", line 58, in <module>
        ext_modules = cythonize(extensions),
      File "/usr/local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 966, in cythonize
        aliases=aliases)
      File "/usr/local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 810, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/usr/local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 109, in nonempty
        raise ValueError(error_msg)
    ValueError: 'cubature/_cubature.pyx' doesn't match any files

I reproduced on Mac OS 10.14 and Ubuntu 18.04 LTS

**Comment by saullocastro** [comment]
@jbvsmo could you try with this latest release?

**Comment by jbvsmo** [comment]
@saullocastro The exact thing shows up with release 0.14.2
I tried again both on Mac and Ubuntu.

**Comment by jbvsmo** [comment]
It works when I use directly from github:

    python3 -m pip install git+ssh://git@github.com/saullocastro/cubature@master

But I wanted my setup to fetch everything from pypi as using github it requires a build every time.

**Comment by saullocastro** [comment]
@jbvsmo I'm trying to reproduce this error on my Ubuntu...

**Comment by jbvsmo** [comment]
Try adding upgrade and force to make sure it fetches everything again:

    python3 -m pip install cubature --upgrade --force

**Comment by jbvsmo** [comment]
I can reproduce by downloading the tarball and running `python3 setup.py install`
https://files.pythonhosted.org/packages/e1/d9/fc0fa29c98ecc0bb6dd74c6e0a1e73c092c5ae246af786f00329d1b9c2a1/cubature-0.14.2.tar.gz

There is really no `_cubature.pyx` inside the archive. Only `_cubature.c`

Seems like it is already preprocessed to not need cython

**Comment by saullocastro** [comment]
@jbvsmo  I will change this behaviour, adding all needed to compile into the _cubature.pyx

**Comment by saullocastro** [comment]
@jbvsmo  could you try what you did at the beginning, just "pip install cubature"?

**Comment by jbvsmo** [comment]
Awesome! It works on Ubuntu which was my primary goal. 

But on my dev environment (Mac OS) clang rejects the new flags you added at some point.

    clang: error: invalid argument '-dynamic' not allowed with '-static'
    clang: error: unsupported option '-fopenmp'

Can you roll it back?

**Comment by saullocastro** [comment]
@jbvsmo I see... try with the current master branch, if it works I will create a new release

**Comment by jbvsmo** [comment]
Yes, it does! 
BTW, If you want to special case mac like you did for windows, use `sys.platform` instead of `os.name`

Muito obrigado!

**Comment by saullocastro** [comment]
fixed with 0.14.5 release
