### ISSUE TITLE
Ask for help with an integral

### ISSUE THREAD

**Issue by surrutiaquir** [saullocastro/cubature#30]
Hi, I'm using `cubature` to integrate a very complicated function as part of my research. So far, I'm encountering some numerical instabilities in the process, and the function returns `np.nan` for very few cases. Could you let me know if the nature of the algorithm allows to "ignore" those complicated cases (i.e., returning zero when a `nan` arises) in an efficient way? I appreciate your help!

**Comment by saullocastro** [comment]
Dear @surrutiaquir , I suspect this is an issue with the core C cubature package. The NaN values usually appear when you have  square root of negative numbers , or anything creating complex number out of real number algebra. Can you create a reproduceable example?

**Comment by surrutiaquir** [comment]
Hi @saullocastro, It seems like the nature of the functions + the domain make the perfect combination for division by zero and overflow in some of the expressions. Following the suggestions from `StackOverflow`, I was able to write the functions so that I can avoid some of those, but not all of them. So, I'm attaching an example (I apologize for the ugly expressions). So far, this code and `Mathematica` give me the same answer for the values I have been testing, but they are different from another implementation using Monte Carlo. Is this expected? Thanks a lot!
[example.zip](https://github.com/saullocastro/cubature/files/7146854/example.zip)

**Comment by saullocastro** [comment]
@surrutiaquir I am going to your problem now (a bit late I know...). Where do you get the function rdilog from ?

**Comment by saullocastro** [comment]
@surrutiaquir assuming `from scipy.special import spence

def rdilog(x):
	return spence(1-x)`

**Comment by saullocastro** [comment]
@surrutiaquir clearly, there is an issue when `k=0` in the code. This error would happen in any calculation using such functions. I would recommend to create an `if` statement that can predict a new behavior when `k=0`.

**Comment by surrutiaquir** [comment]
> @surrutiaquir I am going to your problem now (a bit late I know...). Where do you get the function rdilog from ?

I used [this](https://github.com/nelsond/dilogarithm) implementation, but `spence` form `scipy.special` also works.

**Comment by surrutiaquir** [comment]
> @surrutiaquir clearly, there is an issue when `k=0` in the code. This error would happen in any calculation using such functions. I would recommend to create an `if` statement that can predict a new behavior when `k=0`.

Thank you, @saullocastro! I'll follow your advice.
