### ISSUE TITLE
ndim == len(xmin) == len(xmax)?

### ISSUE THREAD

**Issue by nschloe** [saullocastro/cubature#37]
I'm playing around with cubature and I was wondering if `ndim` always must be the length of `xmin` and `xmax`. E.g., would the following make any sense?

```python
cubature(
    # ...
    ndim=1,
    xmin=np.zeros(10),
    xmax=np.ones(10),
    vectorized=True,
)
```
Asking because it doesn't throw an error and I don't get what integral(s) it computes.

**Comment by saullocastro** [comment]
dear @nschloe thank you for the question
as the documentation says, if `vectorized=False` your argumentation is correct, however, if `vecgtorized=True` the parameters `xmin` and `xmax` might refer to different integration limits in a vector-valued function, where each returned position may have different integration limits
