### ISSUE TITLE
incorrect error message

### ISSUE THREAD

**Issue by nschloe** [saullocastro/cubature#38]
The following script
```python
from cubature import cubature
import numpy as np

n = 10
d = np.random.rand(n)

def f(x):
    out = np.outer(x, d)
    print(out.shape)
    return out

cubature(
    func=f,
    ndim=1,
    fdim=n,
    xmin=np.zeros(n),
    xmax=np.ones(n),
    vectorized=True,
)
```
gives the error message
```
alueError: Output vector does not have shape=(:, fdim)
```
-- but it does! The error message should probably be made clearer.

**Comment by saullocastro** [comment]
Dear @nschloe , thank you for your question. I've checked today and the error message is correct. In your example, the function is expanding the output array and giving an output that has the row axis larger than the number of integration points evaluated by the function (when vectorized=True)
