### ISSUE TITLE
Pre-defined grid for Integration

### ISSUE THREAD

**Issue by gunterhermann** [saullocastro/cubature#5]
Dear all,

first, I want to use cubature for the integration of a certain function and then, I want to extract the used grid for this integration. In the following, I want to apply this grid for the integration of similar functions. 
Is it possible with Cubature or with the Python wrapper for Cubature to solely perform the integration step with this pre-defined grid?

Thanks in advance for your help.

Best regards,
Gunter

**Comment by saullocastro** [comment]
Dear Günter,

I'll check that for you and give you a feedback soon.

Best Regards,
Saullo Castro

**Comment by saullocastro** [comment]
@gunterhermann  unfortunately it is not possible to use a pre-defined grid of points in a direct and easy way.

As explained here:

https://github.com/saullocastro/cubature/blob/master/cubature/cpackage/README#L96

you would have to generate a file like the clencurt.h:

https://raw.githubusercontent.com/saullocastro/cubature/master/cubature/cpackage/clencurt.h

containing the points and respective weights for the numeric integration.

Let me know if it helped.

Best Regards,
Saullo
