### ISSUE TITLE
error during build

### ISSUE THREAD

**Issue by amrit-poudel** [saullocastro/cubature#7]
I get the following error when I try to build cubature.

python setup.py build
*******************************
gcc: cubature/_test_integrands.c: No such file or directory
gcc: no input files
*********************************
Why is test_integrands.c file missing?

Also,  can this library be used to integrate functions that are defined in C and are callable from python using ctypes?

**Comment by saullocastro** [comment]
@amrit-poudel , could you please try to run

    python setup.py install 

instead?

**Comment by saullocastro** [comment]
@amrit-poudel  thank you for your feedback

I just fixed it. There were two testing functions there weren't working with common C libraries.

To compile in place (without copying to PythonXX/Lib/site-packages) use:

    python setup.py build_ext --inplace clean

and to install

    python setup.py install

**Comment by amrit-poudel** [comment]
I tried 

python setup.py build 
python setup.py install  --prefix=/to/some/folder

but it tires to  create a folder  called  "test-easy-install-17516.write-test' in  lib/python2.7/site-packages/.

Not sure  what is going on here.

**Comment by saullocastro** [comment]
@amrit-poudel  I found [this thread in Stackoverflow that explains that](http://stackoverflow.com/q/7622562/832621). You have to do:

    sudo python setup.py install --prefix=/to/some/folder

**Comment by amrit-poudel** [comment]
I do not have sudo access!

**Comment by saullocastro** [comment]
Then, could you try:

    python setup.py install --home=/to/some/folder/inside/your/home/dir

**Comment by amrit-poudel** [comment]
Does not work. It says the directory  does NOT support .pth files.

I have put the folder in PYTHONPATH

**Comment by saullocastro** [comment]
@amrit-poudel did you solve it by defiing PYTHONPATH?

**Comment by amrit-poudel** [comment]
Nope. it has not worked for me yet.  Thanks for your suggestions!

**Comment by amrit-poudel** [comment]
Why does python setup.py install --prefix=/wherever/I/want  not work ?

**Comment by saullocastro** [comment]
good question... what if you point `PYTHONPATH` to `/wherever/you/want`?

**Comment by amrit-poudel** [comment]
I have PYTHONPATH pointed to /wherever/I/want, but that still does not work. I do not get any error but I do not see any shared object under python2.7/site-packages either, which means the library did not get installed properly, I assume.

**Comment by amrit-poudel** [comment]
I specified full path to the folder in --prefix, and this seems to install the library, but I am just not sure if this is the complete installation. 

Is pytest required to run test? Is it not possible to run unit test using nose?

**Comment by saullocastro** [comment]
Currently the tests will run only with `pytest`. To be sure if the installation worked, go to your `--prefix` folder and look for `.pyd` files. If they are there, it compiled the modules successfully.

How did you manage to install with `prefix`, I tried here and couldn't, even using the full path.

**Comment by amrit-poudel** [comment]
I knew it was not a complete installation. That file you pointed out is missing under /python2.7/site-packages folder (or any other folder for that matter). 

Specifying full path in --prefix does not throw any error during install, but  .pyd file is missing.

I am confused.

**Comment by saullocastro** [comment]
since you are in LInux, are there any `.so` files instead of `.pyd`?

**Comment by amrit-poudel** [comment]
No shared files, as I mentioned before.

**Comment by amrit-poudel** [comment]
I do not get any error during install, but shared file is missing. Why?

**Comment by saullocastro** [comment]
I'm trying to find out. On Windows, if you want it installed to C:\Temp\Lib\site-packages you have to do:

    set PYTHONPATH=C:\Temp\Lib\site-packages
    python setup.py install --prefix="C:\Temp"

and it creates an importable egg there. Could you try it similarly in Linux?

**Comment by amrit-poudel** [comment]
cubature-0.13.0.dev0-py2.7-linux-x86_64.egg easy-install.pth site.py site.pyc


These files, which includes .egg file, are also created in Linux.

But where is the .so file?

**Comment by saullocastro** [comment]
@amrit-poudel  unpack the .egg file to see the shared objects

**Comment by amrit-poudel** [comment]
easy_install somefile.egg  gives me error because i do not have sudo access

**Comment by saullocastro** [comment]
@amrit-poudel  since we solved this installation issue, I kindly ask you to create a new issue for your new question

**Comment by saullocastro** [comment]
The final solution was.

    set prefix=anydirectory
    set PYTHONPATH=%anydirectory%\Lib\site-packages;%PYTHONPATH%
    mkdir %anydirectory%
    python setup.py install --prefix="%anydirectory%"

It will create an `.egg` file that will go to `%anydirectory%\Lib\site-packages`. This file can be unzipped to obtain the importable module, OR, the full path to this `.egg` can be added to `PYTHONPATH` (which can be also done inside a script through `sys.path.append()`.
