### ISSUE TITLE
vectorized cubature example

### ISSUE THREAD

**Issue by amrit-poudel** [saullocastro/cubature#9]
This vectorized function definition in your example folder is not consistent.

https://github.com/saullocastro/cubature/blob/master/examples/ex_volumes.py

def integrand_ellipsoid_v(x_array, a, b, c):
    rho = np.array(x_array[:, 0])
    phi = np.array(x_array[:, 1])
    theta = np.array(x_array[:, 2])
    return a*b*c*rho**2*sin(theta)

Vectorized function should also have npts as its argument, but I do not see it here.

Here you mention how vectorized function should be defined.
https://github.com/saullocastro/cubature/blob/master/cubature/cubature.py

If ``vectorized=True`` the function must have the form:
            ``f(x_array, npt, *args, **kwargs)``
            - `x_array` has ``shape[0]=ndim*npt``

I do not think this is correct.

I thin the correct way is, for a vectorized function,  x_array can be a  2D array  such  that 
shape(x_array) = (npt, ndim) 
size(x_array) = npt*ndim

**Comment by saullocastro** [comment]
The example is correct and the documentation for the vectorized function is outdated. 

Passing `npt` isn't necessary since numpy would perform any operation using the input array without the need to know its size (even here we could use the `shape` attribute to know its size).

I will update the documentation and fix this bug.

**Comment by saullocastro** [comment]
@# I will follow your advice and adopt for a vectorized function the input in the form if a 2D array

**Comment by amrit-poudel** [comment]
Thanks for the update!

**Comment by saullocastro** [comment]
@amrit-poudel  if you see the example here

https://github.com/saullocastro/cubature/blob/master/examples/ex_volumes.py#L18

it will become clear that for a vectorized function the input array is already a 2D array with shape (npt, ndim)

**Comment by saullocastro** [comment]
Closed with commit  https://github.com/saullocastro/cubature/commit/2b0216c0d4a307a14ee7fb41bf1244f94de87125
